# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "docker-compose" 
    directory: "/tests/compose/api/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directory: "/tests/compose/core/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directory: "/tests/compose/fetchmail/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directory: "/tests/compose/filters/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directory: "/tests/compose/webdav/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directory: "/tests/compose/webmail/" # Location of package manifests
    schedule:
      interval: "weekly"
